config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :likes
  resources :user_plants
  resources :users

  resources :sessions, only: [:create]
  resources :registrations, only: [:create, :show]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root to: 'static#home'

end

app/models/user_plant.rb
class UserPlant < ApplicationRecord

    belongs_to :user
    # has_many :users, through: :likes
    has_many :likes, dependent: :destroy
    has_many :user_likes, through: :likes, source: :user
    has_one_attached :image
    has_many :comments, dependent: :destroy

    validates_numericality_of :moisture, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5
    validates_numericality_of :difficulty, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5
    validates_numericality_of :sunlight, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5

end

app/controllers/user_plants_controller.rb
class UserPlantsController < ApplicationController
  before_action :set_user_plant, only: [:show, :edit, :update, :destroy]

  def index
    @user_plants = UserPlant.all
    render json: @user_plants
  end

  def show
    # is this correct way to find plants of that user?
    @user_plants = UserPlant.find_by(params[:user_id])
  end

  def new
    @user_plant = UserPlant.new
  end

  def create
    @user_plant = UserPlant.create!(user_plant_params)
    if @user_plant.save
      render json: {
        status: :created, 
        user_plant: UserPlantSerializer.new(@user_plant)
    }
    else
      render json: { status: 500 }    
    end
  end

  def update
    if @user_plant.update(user_plant_params)
      render json: {
        user_plant: UserPlantSerializer.new(@user_plant),
        status: :updated
      }
    else
      render json: @user_plant.errors, status: :unprocessable_entity 
    end
  end

  def destroy
    @user_plant.destroy
      render json: { 
        status: :destroyed 
      }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_plant
      @user_plant = UserPlant.find(params[:id])
    end

    # do these params makes all these fields REQUIRED?
    # Only allow a list of trusted parameters through.
    def user_plant_params

      params.permit(:common_name, :plant_name, :personality, :insight, :story_notes, :image, :difficulty, :sunlight, :moisture, :user_id, :user_icon, :user_name)

      # params.require(:user_plant).permit(:user_id, :user_fav, :user_icon, :user_name, :monograph_id, :common_name, :plant_name, :personality, :insight, :story_notes, :image_url, :difficulty, :sunlight, :moisture)
    end
end

app/helpers/user_plants_helper.rb
module UserPlantsHelper
end

app/views/user_plants/_form.html.erb
<%= form_with(model: user_plant, local: true) do |form| %>
  <% if user_plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_plant.errors.count, "error") %> prohibited this user_plant from being saved:</h2>

      <ul>
        <% user_plant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_fav %>
    <%= form.check_box :user_fav %>
  </div>

  <div class="field">
    <%= form.label :monograph_id %>
    <%= form.number_field :monograph_id %>
  </div>

  <div class="field">
    <%= form.label :common_name %>
    <%= form.text_field :common_name %>
  </div>

  <div class="field">
    <%= form.label :plant_name %>
    <%= form.text_field :plant_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :personality %>
    <%= form.text_field :personality %>
  </div>

  <div class="field">
    <%= form.label :insight %>
    <%= form.text_field :insight %>
  </div>

  <div class="field">
    <%= form.label :story_notes %>
    <%= form.text_field :story_notes %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.number_field :difficulty %>
  </div>

  <div class="field">
    <%= form.label :sunlight %>
    <%= form.number_field :sunlight %>
  </div>

  <div class="field">
    <%= form.label :moisture %>
    <%= form.number_field :moisture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_plants/edit.html.erb
<h1>Editing User Plant</h1>

<%= render 'form', user_plant: @user_plant %>

<%= link_to 'Show', @user_plant %> |
<%= link_to 'Back', user_plants_path %>

app/views/user_plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Plants</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User fav</th>
      <th>Monograph</th>
      <th>Common name</th>
      <th>Plant name</th>
      <th>Image url</th>
      <th>Personality</th>
      <th>Insight</th>
      <th>Story notes</th>
      <th>Difficulty</th>
      <th>Sunlight</th>
      <th>Moisture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_plants.each do |user_plant| %>
      <tr>
        <td><%= user_plant.user_id %></td>
        <td><%= user_plant.user_fav %></td>
        <td><%= user_plant.monograph_id %></td>
        <td><%= user_plant.common_name %></td>
        <td><%= user_plant.plant_name %></td>
        <td><%= user_plant.image_url %></td>
        <td><%= user_plant.personality %></td>
        <td><%= user_plant.insight %></td>
        <td><%= user_plant.story_notes %></td>
        <td><%= user_plant.difficulty %></td>
        <td><%= user_plant.sunlight %></td>
        <td><%= user_plant.moisture %></td>
        <td><%= link_to 'Show', user_plant %></td>
        <td><%= link_to 'Edit', edit_user_plant_path(user_plant) %></td>
        <td><%= link_to 'Destroy', user_plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Plant', new_user_plant_path %>

app/views/user_plants/new.html.erb
<h1>New User Plant</h1>

<%= render 'form', user_plant: @user_plant %>

<%= link_to 'Back', user_plants_path %>

app/views/user_plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_plant.user_id %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @user_plant.common_name %>
</p>

<p>
  <strong>Plant name:</strong>
  <%= @user_plant.plant_name %>
</p>

<p>
  <strong>Personality:</strong>
  <%= @user_plant.personality %>
</p>

<p>
  <strong>Insight:</strong>
  <%= @user_plant.insight %>
</p>

<p>
  <strong>Story notes:</strong>
  <%= @user_plant.story_notes %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @user_plant.difficulty %>
</p>

<p>
  <strong>Sunlight:</strong>
  <%= @user_plant.sunlight %>
</p>

<p>
  <strong>Moisture:</strong>
  <%= @user_plant.moisture %>
</p>

<%= link_to 'Edit', edit_user_plant_path(@user_plant) %> |
<%= link_to 'Back', user_plants_path %>